### ISSUE TITLE
ERROR No module named 'lap._lapjv'

### ISSUE THREAD

**Issue by lauraslopes** [Adnedvid/Lap-pkg-for-YOLO#1]
Hi! I'm trying to execute BYTETrack, your repository helped me to overcome the "Cannot build lap wheels" but now, when I execute my code I get the error "ModuleNotFoundError: No module named 'lap._lapjv'".

Any thoughts? Have you faced this?

**Comment by Adnedvid** [comment]
> Hi! I'm trying to execute BYTETrack, your repository helped me to overcome the "Cannot build lap wheels" but now, when I execute my code I get the error "ModuleNotFoundError: No module named 'lap._lapjv'".
> 
> Any thoughts? Have you faced this?

I haven't faced that error personally. However it seems like your workspace isn't pointing to the lap files correctly despite them being installed. Did you copy the package into the same location as your other packages?

Also what version of Python are you using? I have used 3.8 and 3.10 with this package in the past.

**Comment by lauraslopes** [comment]
Yes, I copied the package in the env's site-packages directory. I'm using python 3.11.
However, I uninstalled lap and then installed from  [this](https://github.com/gatagat/lap/tree/master ) repository and I could overcome this error. Thank you for your quick response!
